# Generated by Django 5.0.3 on 2024-03-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Job',
            new_name='job',
        ),
    ]
